#include "src/ground_quantity_label.hpp"
#include <cassert>
using SoE::LootFilter::GroundQuantity::MatchesRuleName;
int main() {
    // The exact two label forms generated by the Alt-visible formatter.
    assert(MatchesRuleName("Divine Orb","Divine Orb",1));
    assert(MatchesRuleName("4x Divine Orb","Divine Orb",4));
    assert(MatchesRuleName("12x Exalted Orb","Exalted Orb",12));
    assert(MatchesRuleName("4x CUSTOM ORB","CUSTOM ORB",4));
    // Same name and unit ID alone cannot grant an unrelated count.
    assert(!MatchesRuleName("12x Divine Orb","Divine Orb",4));
    assert(!MatchesRuleName("4x Exalted Orb","Divine Orb",4));
    assert(!MatchesRuleName("4xDivine Orb","Divine Orb",4));
    assert(!MatchesRuleName("0x Divine Orb","Divine Orb",0));
    assert(!MatchesRuleName("1x Divine Orb","Divine Orb",1));
    assert(!MatchesRuleName("40000x Divine Orb","Divine Orb",4));
    assert(!MatchesRuleName("4x Divine Orb (4)","Divine Orb",4));
    assert(!MatchesRuleName("", "Divine Orb", 4));
    assert(!MatchesRuleName("4x Divine Orb", "", 4));
}
